### ISSUE TITLE
Latest merge borked post deletions

### ISSUE THREAD

**Issue by Ma-ryan** [vesta42/myimouto-plus#20]
Attempting to delete a post results in error 500 now.
```
> PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Rails::reportException() must be an instance of Exception, instance of ParseError given, called in /home/lolibooru/myimouto/vendor/railsphp/railsphp/lib/Rails/Rails.php on line 268 and defined in /home/lolibooru/myimouto/vendor/railsphp/railsphp/lib/Rails/Rails.php:295
Stack trace:
#0 /home/lolibooru/myimouto/vendor/railsphp/railsphp/lib/Rails/Rails.php(268): Rails::reportException(Object(ParseError))
#1 [internal function]: Rails::exceptionHandler(Object(ParseError))
#2 {main}
  thrown in /home/lolibooru/myimouto/vendor/railsphp/railsphp/lib/Rails/Rails.php on line 295

>POST /post/destroy
PHP Warning
array_merge(): Argument #1 is not an array 
#0 [internal function]: Rails::errorHandler(2, 'array_merge(): ...', '/home/lolibooru...', 652, Array)
#1 config/default_config.php(652): array_merge(NULL, Array)
#2 app/models/Post/TagMethods.php(193): MyImouto\DefaultConfig->on_commit_tags_hook(Object(Post))
#3 Rails/ActiveRecord/Base.php(636): Post->commit_tags()
#4 Rails/ActiveRecord/Base.php(409): Rails\ActiveRecord\Base->runCallbacks('save', Object(Closure))
#5 Rails/ActiveRecord/Base.php(383): Rails\ActiveRecord\Base->save(Array)
#6 app/models/Post.php(166): Rails\ActiveRecord\Base->updateAttribute('status', 'flagged')
#7 app/models/Post.php(175): Post->flag('Not anime', '2')
#8 app/models/Post.php(186): Post->destroy_with_reason('Not anime', Object(User))
#9 app/controllers/PostController.php(289): Post::static_destroy_with_reason('431194', 'Not anime', Object(User))
#10 Rails/ActionController/Base.php(268): PostController->destroy()
#11 Rails/ActionController/Base.php(238): Rails\ActionController\Base->runAction('destroy')
#12 Rails/Application/Base.php(188): Rails\ActionController\Base->run_request_action()
#13 Rails/Application/Base.php(39): Rails\Application\Base->_run()
#14 public/index.php(3): Rails\Application\Base::dispatchRequest()
#15 {main}
Error context:
```

**Comment by vesta42** [comment]
Actually was working on that right now. See commit 02cca0efa99dfbf5f2a5f136ab20a7ca51025d43 for fix

**Comment by Ma-ryan** [comment]
It's still borked actually.

**Comment by vesta42** [comment]
Not sure why.
Moving `CONFIG()->on_commit_tags_hook($this);` to be below
```
if ($this->isNewRecord() || !$this->new_tags)
            return;
```
should have fixed it. I can delete posts on mine after that change. Is it still not working? Same error?

**Comment by Ma-ryan** [comment]
I am dumb. I forgot to remove the line above it.
